from ospl_rcompass import convert_xls_json_to_dat

if __name__ == "__main__":
    data = {
        "shots": [
            {
                "From": "A1",
                "To": "SS1",
                "Length": "62.45",
                "Azimuth": "104.00",
                "Depth": "12.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "#|P#",
                "Comment": "",
            },
            {
                "From": "SS1",
                "To": "SS2",
                "Length": "23.00",
                "Azimuth": "89.23",
                "Depth": "25.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "#|P#",
                "Comment": "Nice jump promising on the right",
            },
            {
                "From": "SS2",
                "To": "SS3",
                "Length": "105.32",
                "Azimuth": "140.11",
                "Depth": "35.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "",
                "Comment": "Lead to the SW of the main tunnel - going down into a halocline",
            },
            {
                "From": "SS3",
                "To": "SS4",
                "Length": "20.00",
                "Azimuth": "280.00",
                "Depth": "32.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "",
                "Comment": "",
            },
            {
                "From": "SS4",
                "To": "SS5",
                "Length": "12.34",
                "Azimuth": "359.88",
                "Depth": "35.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "",
                "Comment": "",
            },
            {
                "From": "SS5",
                "To": "SS6",
                "Length": "87.23",
                "Azimuth": "1.06",
                "Depth": "67.00",
                "Left": "",
                "Right": "",
                "Up": "",
                "Down": "",
                "Flags": "",
                "Comment": "",
            },
        ],
        "survey_date": "2025-10-06",
        "unit": "feet",
        "cave_name": "Fulford",
        "survey_name": "East Tunnel",
        "survey_team": ["Bob Beckner", "Matt Hansen"],
        "comment": "Super comment",
        "latitude": 25.7741566,
        "longitude": -80.1935973,
        "declination": -12.23,
    }

    print(convert_xls_json_to_dat(data).decode("utf-8"))  # noqa: T201
