from ospl_rcompass import convert_xls_json_to_dat
from ospl_rcompass.models import SurveyData

if __name__ == "__main__":
    data = {
        "shots": [
            {
                "from": "A1",
                "to": "SS1",
                "length": "62.45",
                "azimuth": "104.00",
                "depth": "12.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "#|P#",
                "comment": "",
            },
            {
                "from": "SS1",
                "to": "SS2",
                "length": "23.00",
                "azimuth": "89.23",
                "depth": "25.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "#|P#",
                "comment": "Nice jump promising on the right",
            },
            {
                "from": "SS2",
                "to": "SS3",
                "length": "105.32",
                "azimuth": "140.11",
                "depth": "35.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "",
                "comment": "Lead to the SW of the main tunnel - going down into a halocline",  # noqa: E501
            },
            {
                "from": "SS3",
                "to": "SS4",
                "length": "20.00",
                "azimuth": "280.00",
                "depth": "32.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "",
                "comment": "",
            },
            {
                "from": "SS4",
                "to": "SS5",
                "length": "12.34",
                "azimuth": "359.88",
                "depth": "35.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "",
                "comment": "",
            },
            {
                "from": "SS5",
                "to": "SS6",
                "length": "87.23",
                "azimuth": "1.06",
                "depth": "67.00",
                "left": "",
                "right": "",
                "up": "",
                "down": "",
                "flags": "",
                "comment": "",
            },
        ],
        "survey_date": "2025-10-06",
        "unit": "feet",
        "cave_name": "Fulford",
        "survey_name": "East Tunnel",
        "survey_team": ["Bob Beckner", "Matt Hansen"],
        "comment": "Super comment",
        "latitude": 25.7741566,
        "longitude": -80.1935973,
        "declination": -12.23,
    }

    model = SurveyData.model_validate(data)

    print(convert_xls_json_to_dat(model.model_dump()).decode("utf-8"))  # noqa: T201
