[build-system]
requires = ["maturin>=1.9,<2"]
build-backend = "maturin"

[tool.maturin]
python-source = "src_python"
module-name = "ospl_rcompass._rust_lib"
bindings = "pyo3"
features = ["pyo3/extension-module"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "check-manifest",
    "pre-commit>=4.1,<4.4",
    "maturin>=1.9,<2",
    "ruff>=0.3,<0.15",
    "wheel>=0.45",
]

[project]
name = "ospl-rcompass"
authors = [
    { name = "Zachary Heylmun", email = "zheylmun@gmail.com" },
    { name = "Jonathan Dekhtiar", email = "jonathan@dekhtiar.com" },
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["pydantic>=2.12,<2.13"]
requires-python = ">=3.10"
dynamic = ["description", "version"] # Version is defined in `Cargo.toml`

[project.optional-dependencies]
test = [
    "pytest>=8.0.0,<9.0.0",
    "pytest-cov>=5.0.0,<8.0.0",
    "pytest-dotenv>=0.5.0,<1.0.0",
    "pytest-env>=1.1.3,<2.0.0",
    "pytest-runner>=6.0.0,<7.0.0",
    "pytest-ordering>=0.6,<1.0.0",
    "parameterized>=0.9.0,<0.10",
]

[project.urls]
"Homepage" = "https://pypi.org/project/ospl-rcompass/"
"Bug Reports" = "https://github.com/zheylmun/compass_data/issues"
"Source" = "https://github.com/zheylmun/compass_data"

[tool.pytest.ini_options]
testpaths = ["tests/"]
addopts = "-vvv --cov=ospl_rcompass --cov-report=term-missing"
# addopts = "-vvv --cov=ospl_rcompass --cov-report=term-missing --capture=no"

[tool.isort]
profile = "black"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/migrations/*.py",
    "staticfiles/*",
    "src_python/openspeleo_core/_rust_lib",
]
# Same as Django: https://github.com/cookiecutter/cookiecutter-django/issues/4792.
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "YTT",
    # "ANN", # flake8-annotations: we should support this in the future but 100+ errors atm
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EM",
    "EXE",
    "FA",
    'ISC',
    "ICN",
    "G",
    'INP',
    'PIE',
    "T20",
    'PYI',
    'PT',
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    # "ARG", # Unused function argument
    "PTH",
    "ERA",
    "PD",
    "PGH",
    "PL",
    "TRY",
    "FLY",
    # "NPY",
    # "AIR",
    "PERF",
    # "FURB",
    # "LOG",
    "RUF",
]
ignore = [
    "COM812", # Checks for the absence of trailing commas.
    "DTZ007", # Checks for uses of datetime.datetime.strptime() that lead to naive
    # datetime objects.
    "EM101",  # Checks for the use of string literals in exception constructors.
    "EM102",  # Checks for the use of f-strings in exception constructors.
    "ERA001", # Checks for commented-out Python code.
    "EXE001", # Checks for a shebang directive in a file that is not executable.
    "FBT001", # Checks for the use of boolean positional arguments in function
    # definitions, as determined by the presence of a bool type hint.
    "FBT002", # Checks for the use of boolean positional arguments in function
    # definitions, as determined by the presence of a boolean default value.
    "N806",    # Checks for the use of non-lowercase variable names in functions.
    "N815",    # Checks for class variable names that follow the mixedCase convention.
    "PLR0913", # Checks for function definitions that include too many arguments.
    "PLR2004", # Checks for the use of unnamed numerical constants ("magic") values in
    # comparisons.
    "PYI024", # Checks for uses of collections.namedtuple in stub files.
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
    "S101",   # Use of assert detected https://docs.astral.sh/ruff/rules/assert/
    "S311",   # Checks for uses of cryptographically weak pseudo-random number generators.
    "SIM102", # sometimes it's better to nest
    "TRY003", # Checks for long exception messages that are not defined in the exception
    # class itself.
    "UP009", # Checks for unnecessary UTF-8 encoding declarations.
    "UP038", # Checks for uses of isinstance/issubclass that take a tuple of types for
    # comparison. Deactivated because it can make the code slow:
    # https://github.com/astral-sh/ruff/issues/7871
    "PLR0912", # Checks for functions or methods with too many branches, including (nested)
    # if, elif, and else branches, for loops, try-except clauses, and match and case statements.
    "C901",   # Checks for functions with a high McCabe complexity.
    "DTZ001", # Checks for datetime instantiations that do not specify a timezone.
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# The fixes in extend-unsafe-fixes will require
# provide the `--unsafe-fixes` flag when fixing.
extend-unsafe-fixes = ["UP038"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
force-single-line = true
