# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

@typing.final
class Shot:
    ...

@typing.final
class SurveyData:
    ...

def convert_xls_json_to_dat(data: SurveyData) -> bytes:
    r"""
    A Python-exposed function that returns fixed DAT file bytes.
    """

